{
 "title": "Coin Flip API Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() -  process_start_time_seconds{job=\"coin-api\"}"
    }
   ]
  },
  {
   "title": "Flips per Minute",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(flip_count{job=\"coin-api\"}[1m]) * 60"
    }
   ]
  },
  {
   "title": "Heads per Flip",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "heads_count{job=\"coin-api\"} / flip_count{job=\"coin-api\"}"
    }
   ]
  },
  {
   "title": "Tails per Flip",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tails_count{job=\"coin-api\"} / flip_count{job=\"coin-api\"}"
    }
   ]
  },
  {
   "title": "Coin API CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{name=\"coin-api\"}"
    }
   ]
  },
  {
   "title": "Coin API Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"coin-api\"}"
    }
   ]
  },
  {
   "title": "Total user CPU time spent in seconds",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_user_seconds_total{app=\"coin-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "error_counter{app=\"coin-api\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}